export const NZ_LOCATIONS = [
  "Auckland",
  "Wellington",
  "Christchurch",
  "Hamilton",
  "Tauranga",
  "Dunedin",
  "Palmerston North",
  "Napier",
  "Nelson",
  "Rotorua",
  "New Plymouth",
  "Whangārei",
  "Invercargill",
  "Whanganui",
  "Gisborne",
  "Blenheim",
  "Pukekohe",
  "Timaru",
  "Taupō",
  "Queenstown",
  "Masterton",
  "Levin",
  "Ashburton",
  "Cambridge",
  "Te Awamutu",
  "Oamaru",
  "Kaikoura",
  "Thames",
  "Greymouth",
  "Hokitika",
];
